//created on: Nov 30, 2021
package it.cnr.isti.labsedc.concern.event;
import it.cnr.isti.labsedc.concern.event.ConcernAbstractEvent;
import it.cnr.isti.labsedc.concern.event.ConcernBaseEvent;
import it.cnr.isti.labsedc.concern.event.ConcernDTForecast;
import it.cnr.isti.labsedc.concern.rules.RulesGenerator;

dialect "java"

declare ConcernDTForecast
    @role( event )
    @timestamp( timestamp )
end

rule "autogenRule0"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule1"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule2"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule3"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule4"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule5"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule6"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule7"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule8"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule9"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule10"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule11"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule12"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule13"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule14"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule15"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule16"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule17"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule18"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule19"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule20"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule21"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule22"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule23"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule24"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule25"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule26"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule27"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule28"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule29"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule30"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule31"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule32"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule33"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule34"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule35"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule36"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule37"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule38"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule39"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule40"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule41"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule42"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule43"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule44"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule45"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule46"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule47"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule48"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule49"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule50"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule51"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule52"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule53"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule54"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule55"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule56"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule57"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule58"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule59"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule60"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule61"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule62"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule63"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule64"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule65"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule66"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule67"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule68"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule69"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule70"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule71"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule72"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule73"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule74"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule75"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule76"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule77"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule78"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule79"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule80"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule81"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule82"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule83"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule84"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule85"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule86"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule87"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule88"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule89"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule90"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule91"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule92"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule93"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule94"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule95"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule96"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule97"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule98"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule99"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule100"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule101"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule102"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule103"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule104"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule105"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule106"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule107"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule108"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule109"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule110"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule111"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule112"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule113"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule114"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule115"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule116"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule117"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule118"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule119"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule120"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule121"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule122"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule123"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule124"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule125"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule126"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule127"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule128"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule129"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule130"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule131"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule132"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule133"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule134"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule135"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule136"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule137"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule138"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule139"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule140"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule141"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule142"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule143"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule144"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule145"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule146"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule147"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule148"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule149"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule150"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule151"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule152"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule153"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule154"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule155"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule156"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule157"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule158"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule159"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule160"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule161"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule162"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule163"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule164"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule165"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule166"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule167"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule168"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule169"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule170"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule171"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule172"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule173"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule174"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule175"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule176"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule177"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule178"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule179"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule180"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule181"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule182"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule183"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule184"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule185"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule186"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule187"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule188"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule189"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule190"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule191"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule192"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule193"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule194"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule195"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule196"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule197"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule198"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule199"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule200"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule201"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule202"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule203"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule204"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule205"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule206"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule207"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule208"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule209"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule210"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule211"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule212"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule213"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule214"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule215"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule216"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule217"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule218"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule219"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule220"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule221"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule222"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule223"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule224"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule225"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule226"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule227"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule228"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule229"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule230"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule231"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule232"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule233"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule234"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule235"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule236"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule237"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule238"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule239"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule240"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule241"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule242"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule243"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule244"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule245"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule246"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule247"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule248"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule249"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule250"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule251"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule252"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule253"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule254"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule255"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule256"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule257"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule258"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule259"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule260"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule261"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule262"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule263"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule264"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule265"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule266"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule267"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule268"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule269"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule270"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule271"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule272"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule273"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule274"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule275"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule276"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule277"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule278"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule279"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule280"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule281"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule282"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule283"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule284"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule285"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule286"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule287"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule288"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule289"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule290"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule291"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule292"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule293"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule294"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule295"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule296"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule297"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule298"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end

rule "autogenRule299"
no-loop
salience 10
dialect "java"
when
$aEvent : ConcernDTForecast(
this.getSenderID == "DigitalTwin",
this.getDestinationID == "Monitoring");
then
RulesGenerator.generateRuleFromDTForecast($aEvent);
retract($aEvent);	
end